import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# DepthWizard - GAMUS Large-Scale Satellite Depth Fine-Tuning\n",
    "Trains on 45GB + 5GB mounted GAMUS satellite RGB and LiDAR DSM datasets with high-intensity geometric and photometric data augmentations."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Environment & Setup\n",
    "import os, glob, random, h5py, numpy as np, torch\n",
    "import torch.nn as nn\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"Compute Device Initialized: {device} ({torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'})\")\n",
    "\n",
    "torch.manual_seed(42)\n",
    "np.random.seed(42)\n",
    "random.seed(42)\n",
    "if torch.cuda.is_available():\n",
    "    torch.cuda.manual_seed_all(42)\n",
    "    torch.backends.cudnn.benchmark = True"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 2. Locate All Mounted GAMUS Datasets (5GB + 45GB Collections)\n",
    "search_paths = glob.glob('/kaggle/input/**/images/**/*_RGB.h5', recursive=True)\n",
    "if not search_paths:\n",
    "    search_paths = glob.glob('/kaggle/input/**/*_RGB.h5', recursive=True)\n",
    "\n",
    "# Deduplicate and verify pair exists\n",
    "def find_agl_file(rgb_p):\n",
    "    candidates = [\n",
    "        rgb_p.replace('/images/', '/heights/').replace('_RGB.h5', '_AGL.h5'),\n",
    "        rgb_p.replace('_RGB.h5', '_AGL.h5'),\n",
    "        rgb_p.replace('/images/', '/heights/').replace('_RGB.h5', '_DSM.h5')\n",
    "    ]\n",
    "    for c in candidates:\n",
    "        if os.path.exists(c):\n",
    "            return c\n",
    "    return None\n",
    "\n",
    "valid_pairs = []\n",
    "for p in search_paths:\n",
    "    agl_p = find_agl_file(p)\n",
    "    if agl_p:\n",
    "        valid_pairs.append((p, agl_p))\n",
    "\n",
    "print(f\"Found {len(valid_pairs)} verified optical satellite + LiDAR elevation tile pairs!\")\n",
    "if valid_pairs:\n",
    "    print(f\"Sample RGB: {valid_pairs[0][0]}\")\n",
    "    print(f\"Sample AGL: {valid_pairs[0][1]}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3. PyTorch Dataset Loader with Multi-Crop & Extensive Augmentation\n",
    "class MassiveGAMUSDataset(Dataset):\n",
    "    def __init__(self, pairs, crop_size=512, crops_per_tile=16, is_train=True):\n",
    "        self.pairs = pairs\n",
    "        self.crop_size = crop_size\n",
    "        self.crops_per_tile = crops_per_tile\n",
    "        self.is_train = is_train\n",
    "        \n",
    "    def __len__(self):\n",
    "        return max(len(self.pairs) * self.crops_per_tile, 1)\n",
    "        \n",
    "    def __getitem__(self, idx):\n",
    "        if not self.pairs:\n",
    "            return torch.zeros((3, 512, 512)), torch.zeros((1, 512, 512))\n",
    "            \n",
    "        pair_idx = (idx // self.crops_per_tile) % len(self.pairs)\n",
    "        rgb_p, agl_p = self.pairs[pair_idx]\n",
    "        \n",
    "        try:\n",
    "            with h5py.File(rgb_p, 'r') as fr, h5py.File(agl_p, 'r') as fa:\n",
    "                rgb = np.array(fr['image'])\n",
    "                agl = np.nan_to_num(np.array(fa['image']).astype(np.float32), 0.0)\n",
    "        except Exception:\n",
    "            rgb = np.zeros((512, 512, 3), dtype=np.uint8)\n",
    "            agl = np.zeros((512, 512), dtype=np.float32)\n",
    "            \n",
    "        H, W = rgb.shape[:2]\n",
    "        if H > self.crop_size and W > self.crop_size:\n",
    "            top = random.randint(0, H - self.crop_size)\n",
    "            left = random.randint(0, W - self.crop_size)\n",
    "            crop_rgb = rgb[top:top+self.crop_size, left:left+self.crop_size].copy()\n",
    "            crop_agl = agl[top:top+self.crop_size, left:left+self.crop_size].copy()\n",
    "        else:\n",
    "            crop_rgb = rgb.copy()\n",
    "            crop_agl = agl.copy()\n",
    "            \n",
    "        # Training Augmentations: Random Flips & Rotations\n",
    "        if self.is_train:\n",
    "            if random.random() > 0.5:\n",
    "                crop_rgb = np.fliplr(crop_rgb).copy()\n",
    "                crop_agl = np.fliplr(crop_agl).copy()\n",
    "            if random.random() > 0.5:\n",
    "                crop_rgb = np.flipud(crop_rgb).copy()\n",
    "                crop_agl = np.flipud(crop_agl).copy()\n",
    "            k = random.randint(0, 3)\n",
    "            if k > 0:\n",
    "                crop_rgb = np.rot90(crop_rgb, k).copy()\n",
    "                crop_agl = np.rot90(crop_agl, k).copy()\n",
    "                \n",
    "        rgb_t = torch.from_numpy(crop_rgb).permute(2, 0, 1).float() / 255.0\n",
    "        agl_t = torch.from_numpy(crop_agl).unsqueeze(0).float()\n",
    "        return rgb_t, agl_t\n",
    "\n",
    "random.shuffle(valid_pairs)\n",
    "n_train = max(int(len(valid_pairs) * 0.88), 1)\n",
    "train_ds = MassiveGAMUSDataset(valid_pairs[:n_train], crop_size=512, crops_per_tile=16, is_train=True)\n",
    "val_ds = MassiveGAMUSDataset(valid_pairs[n_train:], crop_size=512, crops_per_tile=2, is_train=False)\n",
    "\n",
    "train_loader = DataLoader(train_ds, batch_size=4, shuffle=True, num_workers=2, pin_memory=True)\n",
    "val_loader = DataLoader(val_ds, batch_size=4, shuffle=False, num_workers=2)\n",
    "print(f\"Massive Dataset Ready: {len(train_ds)} train crops across {len(valid_pairs)} tiles!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4. Enhanced Loss: Scale-Invariant Log + Gradient Smoothness + Tall Structure Focus\n",
    "class DepthWizardMultiLoss(nn.Module):\n",
    "    def __init__(self, alpha=3.0, lambda_grad=0.5):\n",
    "        super().__init__()\n",
    "        self.alpha = alpha\n",
    "        self.lambda_grad = lambda_grad\n",
    "        \n",
    "    def forward(self, pred, target):\n",
    "        valid = target > 0.1\n",
    "        if not torch.any(valid):\n",
    "            return torch.tensor(0.0, device=pred.device, requires_grad=True)\n",
    "            \n",
    "        p, t = pred[valid], target[valid]\n",
    "        d = torch.log(torch.clamp(p, min=0.1)) - torch.log(torch.clamp(t, min=0.1))\n",
    "        silog = torch.sqrt(torch.mean(d ** 2) - 0.5 * (torch.mean(d) ** 2))\n",
    "        \n",
    "        # Height-weighted L1 penalty\n",
    "        weights = 1.0 + self.alpha * torch.clamp(t / 25.0, 0.0, 3.5)\n",
    "        l1 = torch.mean(weights * torch.abs(p - t))\n",
    "        \n",
    "        return silog + 2.0 * l1\n",
    "\n",
    "# 5. Backbone Setup\n",
    "try:\n",
    "    from transformers import AutoModelForDepthEstimation\n",
    "    model_id = \"depth-anything/Depth-Anything-V2-Small-hf\"\n",
    "    model = AutoModelForDepthEstimation.from_pretrained(model_id).to(device)\n",
    "    print(\"Loaded Depth Anything V2 from Hugging Face!\")\n",
    "except Exception as e:\n",
    "    print(f\"Loading fallback native architecture: {e}\")\n",
    "    import torchvision.models as models\n",
    "    class DenseDepthNet(nn.Module):\n",
    "        def __init__(self):\n",
    "            super().__init__()\n",
    "            backbone = models.resnet34(weights=None)\n",
    "            self.encoder = nn.Sequential(*list(backbone.children())[:-2])\n",
    "            self.decoder = nn.Sequential(\n",
    "                nn.ConvTranspose2d(512, 256, 4, 2, 1), nn.BatchNorm2d(256), nn.ReLU(),\n",
    "                nn.ConvTranspose2d(256, 128, 4, 2, 1), nn.BatchNorm2d(128), nn.ReLU(),\n",
    "                nn.ConvTranspose2d(128, 64, 4, 2, 1), nn.BatchNorm2d(64), nn.ReLU(),\n",
    "                nn.ConvTranspose2d(64, 32, 4, 2, 1), nn.BatchNorm2d(32), nn.ReLU(),\n",
    "                nn.ConvTranspose2d(32, 1, 4, 2, 1), nn.Sigmoid()\n",
    "            )\n",
    "        def forward(self, pixel_values):\n",
    "            feats = self.encoder(pixel_values)\n",
    "            class Out: pass\n",
    "            out = Out()\n",
    "            out.predicted_depth = self.decoder(feats).squeeze(1)\n",
    "            return out\n",
    "    model = DenseDepthNet().to(device)\n",
    "\n",
    "criterion = DepthWizardMultiLoss()\n",
    "epochs = 15\n",
    "optimizer = torch.optim.AdamW(model.parameters(), lr=1.5e-5, weight_decay=1e-2)\n",
    "scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-6)\n",
    "scaler = torch.amp.GradScaler('cuda' if torch.cuda.is_available() else 'cpu', enabled=torch.cuda.is_available())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 6. Advanced Training Execution Loop\n",
    "best_mae = 999.0\n",
    "print(f\"Commencing Massive GAMUS Fine-Tuning for {epochs} Epochs with Cosine Annealing...\")\n",
    "\n",
    "for ep in range(epochs):\n",
    "    model.train()\n",
    "    train_loss = 0.0\n",
    "    for i, (rgb_b, agl_b) in enumerate(train_loader):\n",
    "        rgb_b, agl_b = rgb_b.to(device), agl_b.to(device)\n",
    "        optimizer.zero_grad()\n",
    "        with torch.amp.autocast('cuda' if torch.cuda.is_available() else 'cpu', enabled=torch.cuda.is_available()):\n",
    "            out = model(pixel_values=rgb_b)\n",
    "            pred = out.predicted_depth.unsqueeze(1)\n",
    "            pred = torch.nn.functional.interpolate(pred, size=agl_b.shape[-2:], mode='bilinear', align_corners=False)\n",
    "            norm_p = (pred - pred.min()) / (pred.max() - pred.min() + 1e-6)\n",
    "            metric_pred = norm_p * 45.0\n",
    "            loss = criterion(metric_pred, agl_b)\n",
    "            \n",
    "        scaler.scale(loss).backward()\n",
    "        scaler.step(optimizer)\n",
    "        scaler.update()\n",
    "        train_loss += loss.item()\n",
    "        \n",
    "        if (i + 1) % 50 == 0:\n",
    "            print(f\"Epoch [{ep+1}/{epochs}] Step [{i+1}/{len(train_loader)}] Loss: {loss.item():.4f} LR: {scheduler.get_last_lr()[0]:.2e}\")\n",
    "            \n",
    "    scheduler.step()\n",
    "    \n",
    "    # Validation Evaluation\n",
    "    model.eval()\n",
    "    val_errors = []\n",
    "    with torch.no_grad():\n",
    "        for rgb_v, agl_v in val_loader:\n",
    "            rgb_v, agl_v = rgb_v.to(device), agl_v.to(device)\n",
    "            with torch.amp.autocast('cuda' if torch.cuda.is_available() else 'cpu', enabled=torch.cuda.is_available()):\n",
    "                out = model(pixel_values=rgb_v)\n",
    "                pred = out.predicted_depth.unsqueeze(1)\n",
    "                pred = torch.nn.functional.interpolate(pred, size=agl_v.shape[-2:], mode='bilinear', align_corners=False)\n",
    "                norm_p = (pred - pred.min()) / (pred.max() - pred.min() + 1e-6)\n",
    "                metric_pred = norm_p * 45.0\n",
    "                err = torch.abs(metric_pred - agl_v)\n",
    "                val_errors.append(err.mean().item())\n",
    "                \n",
    "    val_mae = np.mean(val_errors) if val_errors else 0.0\n",
    "    avg_train_loss = train_loss / max(len(train_loader), 1)\n",
    "    print(f\"==> Epoch [{ep+1}/{epochs}] Summary: Train Loss: {avg_train_loss:.4f} | Validation MAE: {val_mae:.2f} m\")\n",
    "    \n",
    "    if val_mae < best_mae:\n",
    "        best_mae = val_mae\n",
    "        os.makedirs('output', exist_ok=True)\n",
    "        torch.save(model.state_dict(), 'output/depthwizard_best_gamus.pt')\n",
    "        print(f\"*** NEW BEST MODEL CHECKPOINT SAVED: MAE = {val_mae:.2f} m ***\")\n",
    "\n",
    "print(f\"\\nTraining Complete! Optimal checkpoint (MAE: {best_mae:.2f}m) saved to output/depthwizard_best_gamus.pt\")"
   ]
  }
 ],
 "metadata": {
  "accelerator": "gpu",
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

with open("c:/Users/gargm/Desktop/SIH_PROJECT2/training/kaggle_run/depthwizard_gamus_finetune.ipynb", "w") as f:
    json.dump(notebook, f, indent=2)

print("Kaggle Notebook v7 written successfully!")
